apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-web-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lblnginx
  template:
    metadata:
      labels:
        app: lblnginx
    spec:
      containers:
      - name: my-nginx
        image: nginx